---
- name: Customizing Parrot
  hosts: localhost

  roles:
    - role: configure-tmux
      tags: [tmux]
    - role: configure-terminal
      tags: [terminal]
    - role: install-tools
      tags: [tools]
